### PR TITLE
Create a .sublime-syntax and use `embed` to embed JS in it

### PR DESCRIPTION
**Pull request by MatthiasPortzel**
Per discussion in #110.

I'll update this PR or make a new PR with README and documentation changes later (depending on my availability), but this is the main fix.

### CODE REVIEW

**Comment by daaain** [comment]
I cloned this to `~/Library/Application Support/Sublime Text 3/Packages/User/Handlebars` for testing – had to remind myself how to do development on the package 😅

The good thing is that apparently ST4 takes over that ST3 folder so it's easy to share settings and the package.

Seems to work in both versions when looking at the test file.

ST4:

Screenshot 2023-10-01 at 19 53 11

ST3:

image

I'm happy to merge this and have a new version going out so more people can test it and as you say we can update the documentation if / once it's working fine?

**Comment by MatthiasPortzel** [comment]
@daaain I've added a sentence to the README in this PR.

I just want to avoid bike-shedding the README wording here because there are a number of other updates that should be made to the README.

**Comment by daaain** [comment]
README addition sounds good, sorry for the delay and thanks for your contribution, merging and releasing now!

**Comment by MatthiasPortzel** [comment]
I just wanted to say thanks for merging this; I'm using the version from package control and it's working great.

**Pull request merged**
